Hergoku
dulwin/ezebot pull request #3
Opened 2016-09-24 13:24 UTC by vishalkuo

* This guy isn't ready yet but I'd like to consolidate these branches once sqlite is sucessfully working

2016-09-26 23:51 UTC, tanatorn requested changes
Ay

2016-09-26 23:51 UTC, tanatornn96 commented on main.go
> +          go messageHandler(ev, rtm)
Maybe buffer this - probably not gonna be a problem right now, but make it so it's like only some threshold event at the same time?

2016-09-26 23:51 UTC, tanatornn96 commented on main.go
> +  data, err := ioutil.ReadFile("keys/api_key.txt")
if we're using Heroku, can't we just use `heroku local` and put the keys into an `.env` file?

2016-09-26 23:51 UTC, tanatornn96 commented on main.go
> +func spawn_server(){
isn't go camel case?

2016-09-28 01:17 UTC, vishalkuo commented on main.go
> +  data, err := ioutil.ReadFile("keys/api_key.txt")
Good idea, I can't commit the slack key publicly (slack actually disables the key if it finds it on the web) so... Just message me for the env file

2016-09-28 01:25 UTC, vishalkuo commented on main.go
> +  data, err := ioutil.ReadFile("keys/api_key.txt")
Actually I can't even get it to work at the moment. Let me know if you have better luck

2016-09-28 01:51 UTC, tanatorn approved these changes

2016-09-28 01:51 UTC, tanatornn96 commented
LGTM

2016-09-28 01:52 UTC, merged